# Generated by Django 3.2.13 on 2022-11-03 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_imagelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehotplace',
            name='hotplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='reviews.hotplace'),
        ),
        migrations.AlterField(
            model_name='imagelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='reviews.location'),
        ),
        migrations.AlterField(
            model_name='imagereviews',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='reviews.reviews'),
        ),
    ]
