# Generated by Django 3.2.13 on 2022-11-04 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_auto_20221103_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='like_user',
            field=models.ManyToManyField(related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
