# Generated by Django 3.2.13 on 2022-11-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221104_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplace',
            name='x',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='y',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
