# Generated by Django 3.2.13 on 2022-11-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20221104_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplace',
            name='addr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
